### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by xVir** [api-ai/api-ai-android-sdk#3]
Recognition doesn't work with Bluetooth headset

**Comment by nsp4real** [comment]
Why not,"Recognition doesn't work with Bluetooth headset" this explains a
lot of some of my frustration with this software I bought with a life long
ownership subscription, and FYI  I haven't be able to enjoy my lab top
version of product due to not reaction to my Laptop's mic's for speech
recognition? can u explain?

Is there going to be a fix to remedy this so i can keep program running and
still use my bluetooth
If not you should

Also who or where and how do I submit support tickets to my AI API
assistant that i purchased the life long package  to request improvement or
errors in programming so that the AI part can feel more not bullshit.  I
was promised a life long use of.  this program with unlimited request
allowed to be submitted i just never got the detail on where or how  can u
tell me please

I Have a few other issues with my assistant that need to be addressed and
fixed or i'm going to put a refund request for "product not as describe"
 alternatively i would like this problems and non compatibility issues i'm
experiencing with my AI API assistant fixed so i may keep and enjoy the
benefits of intent.

Thank you,
Noah Patton (509)981-3513
nsp4real@gmail.com




*Contact me by cell @ (509)981-3513 or email me at **   nsp4real@gmail.com
<nsp4real@gmail.com>*

**Comment by xVir** [comment]
Hi, @nsp4real!
This section is only intended to the discussions about Android API.AI SDK.
All questions related to Speaktoit Assistant please send to the support: speaktous@speaktoit.com
Thanks!
